### ISSUE TITLE
Support Async / Await

### ISSUE THREAD

**Issue by hoangmy92** [nrempel/adonis-storage#8]
Do you need a hand to add **async** syntax? I could help :)

**Comment by nrempel** [comment]
hi @hoangmy92, if you would like to submit a pull request to support AdonisJS V4 that would be great!

The latest version still only supports Adonis 3.x

**Comment by hoangmy92** [comment]
Sorry for the long response.
Seems they have developed their own plugin https://github.com/adonisjs/adonis-drive
